spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/blog?serverTimezone=Asia/Seoul
        driver-class-name: org.mariadb.jdbc.Driver
        username: nanxi
        password: 111

    